[프로필수정]키워드추가
boostcampwm-2022/android08-KiwiTalk pull request #98
Opened 2022-12-01 14:50 UTC by SteelZoo

2022-12-02 12:13 UTC, choius323 requested changes

2022-12-02 12:13 UTC, choius323 commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileViewModel.kt
> +        }
client를 ViewModel에 넣고 데이터를 가져오는 게 맞을까요?
data source의 역할 같습니다

2022-12-02 12:13 UTC, choius323 commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileViewModel.kt
> +                updateUser(user).enqueue()
여기도 마찬가지로 data source가 해야 될 거 같습니다

2022-12-02 12:13 UTC, choius323 commented on app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
> +        chatViewModel.placeChatInfo.observe(viewLifecycleOwner) { placeChatInfo ->
commit을 따로 분리해주세요

2022-12-02 12:13 UTC, choius323 commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileSettingFragment.kt
> +        }
selectedKeyword는 값이 언제 바뀌는 건가요?
그리고 갱신이 실시간으로 될 필요가 없으면 observe까지 필요하진 않을 거 같습니다.

2022-12-02 13:14 UTC, SteelZoo commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileViewModel.kt
> +        }
저번 멘토님의 리뷰를 듣고 chatClient의 위치에대해 생각을 해봤는데 있는곳에 따라서 역할이 달라진다고 생각했습니다. 일단 지금은 repository나 datasource를 도입하기에는 너무나도 단순한 로직이고 심지어 위의 코드는 이미 chatClient에서 이미 변수상태로 갖고있는 user를 가져오는 것이기에 굳이 깊이를 더 늘려여할까? 라는 생각에 작성했습니다

2022-12-02 13:16 UTC, SteelZoo commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileViewModel.kt
> +                updateUser(user).enqueue()
이 부분은 위에 답에서 말한 이유때문에 그냥 작성하긴했는데 repository 밑으로 작성해야할거 같다고 생각하긴 했습니다

2022-12-02 13:20 UTC, SteelZoo commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileSettingFragment.kt
> +        }
searchkeywordViewmodel을 기준으로 프로필 수정에서 키워드를 그리고 있습니다

2022-12-02 15:31 UTC, choius323 commented on app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileSettingFragment.kt
> +        }
selectedKeyword.observe와 selectedKeyword.value의 성능에 차이가 있을까요?
observe로 하는 것 보단 value로 하는 게 메모리를 덜 쓴다고 생각했는데 테스트해볼 수 있을 지 궁금하네요

2022-12-03 10:04 UTC, choius323 approved these changes

2022-12-03 10:04 UTC, merged